#!/usr/bin/env bash

# Copyright (c) 2020 Karl, Ryan <brightycloud@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the copyright holder nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

TOUCHPAD="SynPS/2 Synaptics TouchPad"
TRACKPOINT="TPPS/2 Elan TrackPoint"
KEYBOARD="AT Translated Set 2 keyboard"
declare -a devices=( "$TOUCHPAD" "$TRACKPOINT" "$KEYBOARD" )
export DISPLAY=:0
CMD=$(basename "$0" | cut -d- -f2)
if [[ $CMD = "disable" ]];then
  for i in "${devices[@]}";do
    eval $(printf 'xinput disable "%s"\n' "$i")
    printf 'Disabled "%s"\n' "$i" 1>&2
  done
elif [[ $CMD = "enable" ]];then
  for i in "${devices[@]}";do
    eval $(printf 'xinput enable "%s"\n' "$i")
    printf 'Enabled "%s"\n' "$i" 1>&2
  done
fi
